name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cache key
        id: cache_key
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            KEY="${{ runner.os }}-build-$(git rev-parse --short HEAD)-$(sha1sum CMakeLists.txt 2>/dev/null | cut -d' ' -f1 2>/dev/null || echo unknown)"
            echo "CACHE_KEY=$KEY" >> $GITHUB_OUTPUT
          else
            $key = "${{ runner.os }}-build-$((git rev-parse --short HEAD))"
            Write-Output "CACHE_KEY=$key" >> $env:GITHUB_OUTPUT
          fi
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        if: matrix.os == ''ubuntu-latest''

      - name: Set up cache key Windows
        id: cache_key_win
        run: |
          $key = "${{ runner.os }}-build-$(git rev-parse --short HEAD)"
          echo "CACHE_KEY=$key" >> $env:GITHUB_OUTPUT
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Cache build dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        if: matrix.os == ''windows-latest''

      - name: Cache build dependencies (Linux)
        if: matrix.os == ''ubuntu-latest''
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            build
          key: ${{ steps.cache_key.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Cache build dependencies (Windows)
        if: matrix.os == 'windows-latest'
        if: matrix.os == ''windows-latest''
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\cache
            build
          key: ${{ steps.cache_key_win.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Ninja on Linux
        if: matrix.os == 'ubuntu-latest'
        if: matrix.os == ''ubuntu-latest''
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
        shell: bash

      - name: Install Ninja on Windows
        if: matrix.os == 'windows-latest'
        if: matrix.os == ''windows-latest''
        run: choco install ninja -y
        shell: pwsh

      - name: Configure CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        if: matrix.os == ''ubuntu-latest''
        run: cmake -S . -B build -G Ninja
        shell: bash

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        if: matrix.os == ''windows-latest''
        run: cmake -S . -B build -G Ninja
        shell: pwsh

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        if: matrix.os == ''ubuntu-latest''
        run: cmake --build build -- -j$(nproc)
        shell: bash

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        if: matrix.os == ''windows-latest''
        run: cmake --build build -- /m:2
        shell: pwsh

      - name: Smoke test (Linux)
        if: matrix.os == 'ubuntu-latest'
        if: matrix.os == ''ubuntu-latest''
        run: echo "Build succeeded on $RUNNER_OS"
        shell: bash

      - name: Smoke test (Windows)
        if: matrix.os == 'windows-latest'
        run: Write-Output "Build succeeded on $env:RUNNER_OS"
        shell: pwsh

        if: matrix.os == ''windows-latest''
        run: Write-Output "Build succeeded on $env:RUNNER_OS"
        shell: pwsh

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build/logs || build
