name: CI

on:
  push:
    branches:
      - main
      - 'ci/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake and Ninja
        run: |
          choco install -y cmake ninja
          RefreshEnv
        shell: pwsh

      - name: Ensure build directory
        run: New-Item -ItemType Directory -Force -Path build
        shell: pwsh

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja
        shell: pwsh

      - name: Build
        run: cmake --build build --config Release -- /m
        shell: pwsh

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
        shell: pwsh

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: cmake-build-logs-windows
          path: build


