name: CI

on:
  push:
    branches:
      - main
      - 'ci/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: actions/setup-cmake@v3
        with:
          cmake-version: '3.27' # choose a stable recent version

      - name: Ensure Ninja available on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build
        shell: bash

      - name: Ensure Ninja available on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y ninja
        shell: pwsh

      - name: Create build directory
        run: mkdir -p build
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Create build directory (Windows)
        run: New-Item -ItemType Directory -Force -Path build
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Configure CMake (Windows)
        run: cmake -S . -B build -G Ninja
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Build
        run: cmake --build build --config Release -- -j
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Build (Windows)
        run: cmake --build build --config Release -- /m
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure
        shell: bash
        if: matrix.os == 'ubuntu-latest'

      - name: Run tests (Windows)
        run: |
          ctest --test-dir build --output-on-failure
        shell: pwsh
        if: matrix.os == 'windows-latest'

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: cmake-build-logs-${{ matrix.os }}
          path: build
