- name: Configure and build
  uses: ilammy/msvc-dev-cmd@v1
  with:
    arch: amd64
  env:
    CMAKE_GENERATOR: Ninja
  run: |
    choco install ninja -y
    cmake -S . -B build -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=Release
    cmake --build build --config Release
