- name: Cache build dependencies
  uses: actions/cache@v4
  with:
    path: |
      ~/.cache
      build
    key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}-v1
    restore-keys: |
      ${{ runner.os }}-build-


