name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up cache key
        id: cache_key
        run: |
          echo "CACHE_KEY=${{ runner.os }}-build-$(git rev-parse --short HEAD)-$(sha1sum CMakeLists.txt 2>/dev/null | cut -d' ' -f1 2>/dev/null || echo unknown)" >> $GITHUB_OUTPUT
        shell: ${{ matrix.shell }}

      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            build
          key: ${{ steps.cache_key.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Ninja on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
        shell: bash

      - name: Install Ninja on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install ninja -y
        shell: pwsh

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja
        shell: ${{ matrix.shell }}

      - name: Build
        run: |
          cmake --build build -- -j$(nproc 2>/dev/null || echo 2)
        shell: ${{ matrix.shell }}

      - name: Smoke test
        run: |
          echo "Build succeeded on $RUNNER_OS"
        shell: ${{ matrix.shell }}


